name: Check code

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.16.3
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        args: -E gosec -E goconst

    - name: Check if go.sum is up to date
      run: |
        go mod tidy && git diff --exit-code

    - name: Check if imports are properly sorted
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        if [[ -n $(goimports -local github.com/${GITHUB_REPOSITORY} -l .) ]]
        then
          goimports -local github.com/${GITHUB_REPOSITORY} -d .
          exit 1
        fi

    - name: Run go vet
      run: |
        CGO_ENABLED=0 go vet ./...
