name: Build and test mailer

on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development

jobs:
  test-mailer:
    name: Test sensebox-mailer
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # no need to setup go or docker, ubuntu-20.04 has
    # reasonable versions installed ok for our use case
    - run: |
        export GOPATH=${HOME}/go

        GO111MODULE=on go get github.com/mailhog/MailHog@v1.0.1
        GO111MODULE=on go get github.com/square/certstrap@7cda9d4

        export PATH=${PATH}:${GOPATH}/bin

        docker build -t ci-mailer .

        ./genCerts.sh

        export SENSEBOX_MAILER_SERVER_CERT=$(cat out/mailer_server.crt)
        export SENSEBOX_MAILER_SERVER_KEY=$(cat out/mailer_server.key)
        export SENSEBOX_MAILER_CA_CERT=$(cat out/openSenseMapCA.crt)
        export SENSEBOX_MAILER_SMTP_SERVER=localhost
        export SENSEBOX_MAILER_SMTP_PORT=1025
        export SENSEBOX_MAILER_SMTP_USER=smtpuser
        export SENSEBOX_MAILER_SMTP_PASSWORD=smtppassword
        export SENSEBOX_MAILER_FROM_DOMAIN=sensebox.de
        export SENSEBOX_MAILER_FROM_NAME_PREFIX=senseBox

        docker run --rm -it \
          --network=host \
          -e SENSEBOX_MAILER_SERVER_CERT \
          -e SENSEBOX_MAILER_SERVER_KEY \
          -e SENSEBOX_MAILER_CA_CERT \
          -e SENSEBOX_MAILER_SMTP_SERVER \
          -e SENSEBOX_MAILER_SMTP_PORT \
          -e SENSEBOX_MAILER_SMTP_USER \
          -e SENSEBOX_MAILER_SMTP_PASSWORD \
          -e SENSEBOX_MAILER_FROM_DOMAIN \
          -e SENSEBOX_MAILER_FROM_NAME_PREFIX \
          ci-mailer
