name: Build and test mailer

on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development

jobs:
  build-mailer:
    name: build sensebox-mailer
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.3' # The Go version to download (if necessary) and use.

    - run: |
        docker build -t ci-mailer .


  build-mailhog:
    name: build mailhog
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.3' # The Go version to download (if necessary) and use.

    - run: |
        go get github.com/mailhog/MailHog@v1.0.1
